/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'notes';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String = 'assets/.';
  static const String ADD_NOTES_IMAGE = 'assets/add_notes_image.png';
  static const String IOS_LOADING = 'assets/ios_loading.gif';
}
